# run: conda env create --file environment.yml
name: swift_notes_py3_10
dependencies:
- python=3.10
- bzip2=1.0.8
- ca-certificates=2023.12.12
- libffi=3.4.4
- openssl=3.0.13
- pip=23.3.1
- python=3.10.13
- setuptools=68.2.2
- sqlite=3.41.2
- tk=8.6.12
- tzdata=2023d
- vc=14.2
- vs2015_runtime=14.27.29016
- wheel=0.41.2
- xz=5.4.5
- zlib=1.2.13
- pip:
  - altgraph==0.17.4
  - packaging==23.2
  - pefile==2023.2.7
  - pyinstaller==6.4.0
  - pyinstaller-hooks-contrib==2024.1
  - pyside6==6.6.1
  - pyside6-addons==6.6.1
  - pyside6-essentials==6.6.1
  - pywin32-ctypes==0.2.2
  - shiboken6==6.6.1
